FROM python:3.12-slim@sha256:7a8b475003c4fe15a2cd4e55e5cfc2f3560bdc9333d624f24cdd6d4340fd7a17

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY pyproject.toml readme.md /app/
COPY src /app/src
COPY schemas /app/schemas
COPY challenges /app/challenges
COPY tests/challenges /app/tests/challenges
RUN python -m pip install --no-cache-dir --disable-pip-version-check .

ENTRYPOINT ["python", "-m", "mea_eb5.cli"]
